# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed !(or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create!( name: 'Chicago' ,  name: 'Copenhagen' )
#   Mayor.create!(name: 'Emanuel', city: cities.first)
Student.delete_all
Teacher.delete_all
Subject.delete_all
ClassSection.delete_all
Announcement.delete_all
StudentGradeSubject.delete_all
StudentYearSection.delete_all
# create students
Student.create!(student_lrn: '111111', first_name: 'Student', middle_name: 'Number', last_name: 'One', age: 18, birthdate: '1997-06-01', religion: 'Catholic', contact_no:'09123456789', year_level: 3, password: 'One')
Student.create!(student_lrn: '222222', first_name: 'Student', middle_name: 'Number', last_name: 'Two', age: 18, birthdate: '1997-07-02', religion: 'Catholic', contact_no:'09123456789', year_level: 3, password: 'Two')
Student.create!(student_lrn: '333333', first_name: 'Student', middle_name: 'Number', last_name: 'Three', age: 18, birthdate: '1997-08-03', religion: 'Catholic', contact_no:'09123456789', year_level: 3, password: 'Three')
Student.create!(student_lrn: '444444', first_name: 'Student', middle_name: 'Number', last_name: 'Four', age: 18, birthdate: '1997-09-04', religion: 'Catholic', contact_no:'09123456789', year_level: 3, password: 'Four')
Student.create!(student_lrn: '555555', first_name: 'Student', middle_name: 'Number', last_name: 'Five', age: 18, birthdate: '1997-10-05', religion: 'Catholic', contact_no:'09123456789', year_level: 3, password: 'Five')
# create teachers
Teacher.create!(license_id: '111111', first_name: 'Sample', middle_name: 'Teacher', last_name: 'One', contact_no:'09123456789')
Teacher.create!(license_id: '222222', first_name: 'Sample', middle_name: 'Teacher', last_name: 'Two', contact_no:'09123456789')
Teacher.create!(license_id: '333333', first_name: 'Sample', middle_name: 'Teacher', last_name: 'Three', contact_no:'09123456789')
Teacher.create!(license_id: '444444', first_name: 'Sample', middle_name: 'Teacher', last_name: 'Four', contact_no:'09123456789')
Teacher.create!(license_id: '555555', first_name: 'Sample', middle_name: 'Teacher', last_name: 'Five', contact_no:'09123456789')
# create subjects
Subject.create!(subject_title: 'Subject 1', schedule:'07:30', instructor:'111111')
Subject.create!(subject_title: 'Subject 2', schedule:'08:30', instructor:'222222')
Subject.create!(subject_title: 'Subject 3', schedule:'09:30', instructor:'333333')
Subject.create!(subject_title: 'Subject 4', schedule:'10:30', instructor:'444444')
Subject.create!(subject_title: 'Subject 5', schedule:'11:30', instructor:'555555')
#create class
ClassSection.create!(section_name: 'Section 1', room_number: '101', academic_track:'ESEP', adviser:'111111')
ClassSection.create!(section_name: 'Section 2', room_number: '101', academic_track:'ESEP', adviser:'111111')
ClassSection.create!(section_name: 'Section 3', room_number: '101', academic_track:'ESEP', adviser:'111111')
ClassSection.create!(section_name: 'Section 4', room_number: '101', academic_track:'ESEP', adviser:'111111')
ClassSection.create!(section_name: 'Section 5', room_number: '101', academic_track:'ESEP', adviser:'111111')
#create announcement
Announcement.create!(post_date: '2017-03-01', title: 'Announcement 1', content: 'One Announcement')
Announcement.create!(post_date: '2017-03-02', title: 'Announcement 2', content: 'Two Announcement')
Announcement.create!(post_date: '2017-03-03', title: 'Announcement 3', content: 'Three Announcement')
Announcement.create!(post_date: '2017-03-04', title: 'Announcement 4', content: 'Four Announcement')
Announcement.create!(post_date: '2017-03-05', title: 'Announcement 5', content: 'Five Announcement')
#create student grade subject
StudentGradeSubject.create!(student_lrn: '111111', subject_title: 'Subject 1', quarter: 1, grade: '98.0')
StudentGradeSubject.create!(student_lrn: '111111', subject_title: 'Subject 2', quarter: 1, grade: '89.0')
StudentGradeSubject.create!(student_lrn: '111111', subject_title: 'Subject 3', quarter: 1, grade: '67.0')
StudentGradeSubject.create!(student_lrn: '111111', subject_title: 'Subject 4', quarter: 1, grade: '93.0')
StudentGradeSubject.create!(student_lrn: '111111', subject_title: 'Subject 5', quarter: 1, grade: '76.0')
StudentGradeSubject.create!(student_lrn: '222222', subject_title: 'Subject 1', quarter: 1, grade: '92.0')
StudentGradeSubject.create!(student_lrn: '222222', subject_title: 'Subject 2', quarter: 1, grade: '76.0')
StudentGradeSubject.create!(student_lrn: '222222', subject_title: 'Subject 3', quarter: 1, grade: '84.0')
StudentGradeSubject.create!(student_lrn: '222222', subject_title: 'Subject 4', quarter: 1, grade: '97.0')
StudentGradeSubject.create!(student_lrn: '222222', subject_title: 'Subject 5', quarter: 1, grade: '88.0')
StudentGradeSubject.create!(student_lrn: '333333', subject_title: 'Subject 1', quarter: 1, grade: '76.0')
StudentGradeSubject.create!(student_lrn: '333333', subject_title: 'Subject 2', quarter: 1, grade: '84.0')
StudentGradeSubject.create!(student_lrn: '333333', subject_title: 'Subject 3', quarter: 1, grade: '85.0')
StudentGradeSubject.create!(student_lrn: '333333', subject_title: 'Subject 4', quarter: 1, grade: '77.0')
StudentGradeSubject.create!(student_lrn: '333333', subject_title: 'Subject 5', quarter: 1, grade: '66.0')
StudentGradeSubject.create!(student_lrn: '444444', subject_title: 'Subject 1', quarter: 1, grade: '88.0')
StudentGradeSubject.create!(student_lrn: '444444', subject_title: 'Subject 2', quarter: 1, grade: '75.0')
StudentGradeSubject.create!(student_lrn: '444444', subject_title: 'Subject 3', quarter: 1, grade: '82.0')
StudentGradeSubject.create!(student_lrn: '444444', subject_title: 'Subject 4', quarter: 1, grade: '70.0')
StudentGradeSubject.create!(student_lrn: '444444', subject_title: 'Subject 5', quarter: 1, grade: '86.0')
StudentGradeSubject.create!(student_lrn: '555555', subject_title: 'Subject 1', quarter: 1, grade: '74.0')
StudentGradeSubject.create!(student_lrn: '555555', subject_title: 'Subject 2', quarter: 1, grade: '90.0')
StudentGradeSubject.create!(student_lrn: '555555', subject_title: 'Subject 3', quarter: 1, grade: '70.0')
StudentGradeSubject.create!(student_lrn: '555555', subject_title: 'Subject 4', quarter: 1, grade: '94.0')
StudentGradeSubject.create!(student_lrn: '555555', subject_title: 'Subject 5', quarter: 1, grade: '92.0')

StudentGradeSubject.create!(student_lrn: '111111', subject_title: 'Subject 1', quarter: 2, grade: '98.0')
StudentGradeSubject.create!(student_lrn: '111111', subject_title: 'Subject 2', quarter: 2, grade: '89.0')
StudentGradeSubject.create!(student_lrn: '111111', subject_title: 'Subject 3', quarter: 2, grade: '67.0')
StudentGradeSubject.create!(student_lrn: '111111', subject_title: 'Subject 4', quarter: 2, grade: '93.0')
StudentGradeSubject.create!(student_lrn: '111111', subject_title: 'Subject 5', quarter: 2, grade: '76.0')
StudentGradeSubject.create!(student_lrn: '222222', subject_title: 'Subject 1', quarter: 2, grade: '92.0')
StudentGradeSubject.create!(student_lrn: '222222', subject_title: 'Subject 2', quarter: 2, grade: '76.0')
StudentGradeSubject.create!(student_lrn: '222222', subject_title: 'Subject 3', quarter: 2, grade: '84.0')
StudentGradeSubject.create!(student_lrn: '222222', subject_title: 'Subject 4', quarter: 2, grade: '97.0')
StudentGradeSubject.create!(student_lrn: '222222', subject_title: 'Subject 5', quarter: 2, grade: '88.0')
StudentGradeSubject.create!(student_lrn: '333333', subject_title: 'Subject 1', quarter: 2, grade: '76.0')
StudentGradeSubject.create!(student_lrn: '333333', subject_title: 'Subject 2', quarter: 2, grade: '84.0')
StudentGradeSubject.create!(student_lrn: '333333', subject_title: 'Subject 3', quarter: 2, grade: '85.0')
StudentGradeSubject.create!(student_lrn: '333333', subject_title: 'Subject 4', quarter: 2, grade: '77.0')
StudentGradeSubject.create!(student_lrn: '333333', subject_title: 'Subject 5', quarter: 2, grade: '66.0')
StudentGradeSubject.create!(student_lrn: '444444', subject_title: 'Subject 1', quarter: 2, grade: '88.0')
StudentGradeSubject.create!(student_lrn: '444444', subject_title: 'Subject 2', quarter: 2, grade: '75.0')
StudentGradeSubject.create!(student_lrn: '444444', subject_title: 'Subject 3', quarter: 2, grade: '82.0')
StudentGradeSubject.create!(student_lrn: '444444', subject_title: 'Subject 4', quarter: 2, grade: '70.0')
StudentGradeSubject.create!(student_lrn: '444444', subject_title: 'Subject 5', quarter: 2, grade: '86.0')
StudentGradeSubject.create!(student_lrn: '555555', subject_title: 'Subject 1', quarter: 2, grade: '74.0')
StudentGradeSubject.create!(student_lrn: '555555', subject_title: 'Subject 2', quarter: 2, grade: '90.0')
StudentGradeSubject.create!(student_lrn: '555555', subject_title: 'Subject 3', quarter: 2, grade: '70.0')
StudentGradeSubject.create!(student_lrn: '555555', subject_title: 'Subject 4', quarter: 2, grade: '94.0')
StudentGradeSubject.create!(student_lrn: '555555', subject_title: 'Subject 5', quarter: 2, grade: '92.0')

StudentGradeSubject.create!(student_lrn: '111111', subject_title: 'Subject 1', quarter: 3, grade: '98.0')
StudentGradeSubject.create!(student_lrn: '111111', subject_title: 'Subject 2', quarter: 3, grade: '89.0')
StudentGradeSubject.create!(student_lrn: '111111', subject_title: 'Subject 3', quarter: 3, grade: '67.0')
StudentGradeSubject.create!(student_lrn: '111111', subject_title: 'Subject 4', quarter: 3, grade: '93.0')
StudentGradeSubject.create!(student_lrn: '111111', subject_title: 'Subject 5', quarter: 3, grade: '76.0')
StudentGradeSubject.create!(student_lrn: '222222', subject_title: 'Subject 1', quarter: 3, grade: '92.0')
StudentGradeSubject.create!(student_lrn: '222222', subject_title: 'Subject 2', quarter: 3, grade: '76.0')
StudentGradeSubject.create!(student_lrn: '222222', subject_title: 'Subject 3', quarter: 3, grade: '84.0')
StudentGradeSubject.create!(student_lrn: '222222', subject_title: 'Subject 4', quarter: 3, grade: '97.0')
StudentGradeSubject.create!(student_lrn: '222222', subject_title: 'Subject 5', quarter: 3, grade: '88.0')
StudentGradeSubject.create!(student_lrn: '333333', subject_title: 'Subject 1', quarter: 3, grade: '76.0')
StudentGradeSubject.create!(student_lrn: '333333', subject_title: 'Subject 2', quarter: 3, grade: '84.0')
StudentGradeSubject.create!(student_lrn: '333333', subject_title: 'Subject 3', quarter: 3, grade: '85.0')
StudentGradeSubject.create!(student_lrn: '333333', subject_title: 'Subject 4', quarter: 3, grade: '77.0')
StudentGradeSubject.create!(student_lrn: '333333', subject_title: 'Subject 5', quarter: 3, grade: '66.0')
StudentGradeSubject.create!(student_lrn: '444444', subject_title: 'Subject 1', quarter: 3, grade: '88.0')
StudentGradeSubject.create!(student_lrn: '444444', subject_title: 'Subject 2', quarter: 3, grade: '75.0')
StudentGradeSubject.create!(student_lrn: '444444', subject_title: 'Subject 3', quarter: 3, grade: '82.0')
StudentGradeSubject.create!(student_lrn: '444444', subject_title: 'Subject 4', quarter: 3, grade: '70.0')
StudentGradeSubject.create!(student_lrn: '444444', subject_title: 'Subject 5', quarter: 3, grade: '86.0')
StudentGradeSubject.create!(student_lrn: '555555', subject_title: 'Subject 1', quarter: 3, grade: '74.0')
StudentGradeSubject.create!(student_lrn: '555555', subject_title: 'Subject 2', quarter: 3, grade: '90.0')
StudentGradeSubject.create!(student_lrn: '555555', subject_title: 'Subject 3', quarter: 3, grade: '70.0')
StudentGradeSubject.create!(student_lrn: '555555', subject_title: 'Subject 4', quarter: 3, grade: '94.0')
StudentGradeSubject.create!(student_lrn: '555555', subject_title: 'Subject 5', quarter: 3, grade: '92.0')
#create student year section
StudentYearSection.create!(student_lrn: '111111', year_level: 1, section_name: 'Section 1')
StudentYearSection.create!(student_lrn: '111111', year_level: 2, section_name: 'Section 2')
StudentYearSection.create!(student_lrn: '111111', year_level: 3, section_name: 'Section 3')
StudentYearSection.create!(student_lrn: '222222', year_level: 1, section_name: 'Section 1')
StudentYearSection.create!(student_lrn: '222222', year_level: 2, section_name: 'Section 2')
StudentYearSection.create!(student_lrn: '222222', year_level: 3, section_name: 'Section 3')
StudentYearSection.create!(student_lrn: '333333', year_level: 1, section_name: 'Section 1')
StudentYearSection.create!(student_lrn: '333333', year_level: 2, section_name: 'Section 2')
StudentYearSection.create!(student_lrn: '333333', year_level: 3, section_name: 'Section 3')
StudentYearSection.create!(student_lrn: '444444', year_level: 1, section_name: 'Section 1')
StudentYearSection.create!(student_lrn: '444444', year_level: 2, section_name: 'Section 2')
StudentYearSection.create!(student_lrn: '444444', year_level: 3, section_name: 'Section 3')
StudentYearSection.create!(student_lrn: '555555', year_level: 1, section_name: 'Section 1')
StudentYearSection.create!(student_lrn: '555555', year_level: 2, section_name: 'Section 2')
StudentYearSection.create!(student_lrn: '555555', year_level: 3, section_name: 'Section 3')
##create teacher advise class
#TeacherAdviseClass.create!(teacher_id: '111111', section_name: 'Section 1')
#TeacherAdviseClass.create!(teacher_id: '222222', section_name: 'Section 2')
#TeacherAdviseClass.create!(teacher_id: '333333', section_name: 'Section 3')
#TeacherAdviseClass.create!(teacher_id: '444444', section_name: 'Section 4')
#TeacherAdviseClass.create!(teacher_id: '555555', section_name: 'Section 5')
##create teacher subject section
#TeacherSubjectSection.create!(teacher_id: '111111', subject_title: 'Subject 1', section_name: 'Section 5')
#TeacherSubjectSection.create!(teacher_id: '222222', subject_title: 'Subject 2', section_name: 'Section 4')
#TeacherSubjectSection.create!(teacher_id: '333333', subject_title: 'Subject 3', section_name: 'Section 3')
#TeacherSubjectSection.create!(teacher_id: '444444', subject_title: 'Subject 4', section_name: 'Section 2')
#TeacherSubjectSection.create!(teacher_id: '555555', subject_title: 'Subject 5', section_name: 'Section 1')